/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 background.glb --types 
Author: Conrad Justin (https://sketchfab.com/ConradJustin)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/baker-and-the-bridge-da3f6e7b85ed44b7aa8bb5571e365abc
Title: Baker and the Bridge
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import House from './House';
import Bridge from './Bridge';
import { SHIBA_BG_MATERIALS, SHIBA_BG_NODES } from '@/shared/contants/model';
import Hill from './Hill';

type GLTFResult = GLTF & {
  nodes: SHIBA_BG_NODES;
  materials: SHIBA_BG_MATERIALS;
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

useGLTF.preload('/models/background.glb');

export function Background(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/background.glb') as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <House nodes={nodes} materials={materials} />
          <Bridge nodes={nodes} materials={materials} />
          <Hill nodes={nodes} materials={materials} />
          <mesh
            // 강물
            geometry={nodes.characters008_water_0.geometry}
            material={materials.water}
            rotation={[0, 0, -Math.PI / 2]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}
